### PR TITLE
Add `.env.example` file

### LINKED ISSUE #54: Add enviroment variables documentation
### Feature description

Add a .env.example file so it's easier for people to understand what needs to be filled

### How to implement?

_No response_

### Media, if applicable

_No response_

### PR DESCRIPTION
**Pull request by Piyush-Deshmukh**
Closes #54 
<br>
## What does this PR do?

Added `.env.example` file with content.

## Summary of changes

The content of `.env.example` are :

`TOKEN="dicord-bot-token"`
`MONGODB_URI="mongodb-uri"`
`Authorization="topgg-core-authorization"`

### CODE REVIEW

**Comment by AmarilhaTiago** [comment]
Nice work, my mate! I'll tell about your work for my homies.

**Review by falcao-g — APPROVED** [review]
Nice work!

**Comment by Vicarillous** [comment]
Nice work bro! 👍

**Comment by falcao-g** [comment]
@all-contributors please add @Piyush-Deshmukh for example

**Comment by falcao-g** [comment]
@all-contributors please add @Piyush-Deshmukh for example

**Pull request merged**
